language: node_js
node_js:
- node
- '8'
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
- export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
- yarn global add greenkeeper-lockfile@1
- yarn global add coveralls
- yarn global add codecov
cache: false
install:
- |
  if [[ $BRANCH == "greenkeeper/"* ]]; then
    echo Greenkeeper build; yarn install;
  else
    echo Normal build - frozen lockfile; yarn install --frozen-lockfile;
  fi
before_script: greenkeeper-lockfile-update
script:
- yarn test
- cat ./coverage/lcov.info | coveralls
- codecov -f coverage/coverage-final.json
after_script: greenkeeper-lockfile-upload
stages:
- name: test
- name: deploy
  if: tag =~ ^v AND fork = false AND type = push
jobs:
  include:
  - stage: test
    if: type = cron
    node_js: '8'
    os: osx
    osx_image: xcode9.2
  - stage: test
    if: type = cron
    node_js: '7'
  - stage: test
    if: type = cron
    node_js: '6'
  - stage: test
    if: type = cron
    node_js: '5'
  - stage: test
    if: type = cron OR tag =~ ^v
    node_js: '4'
  - stage: deploy
    before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
    - export PATH=$HOME/.yarn/bin:$PATH
    install: []
    before_script: []
    script:
      - yarn install --frozen-lockfile
      - yarn prepublish
    after_script: []
    before_deploy: yarn tidy-ci
    deploy:
      provider: npm
      email: github-external-bot@holvonix.com
      skip_cleanup: true
      api_key: "$NPM_API_KEY"
      on:
        tags: true
env:
  global:
  - secure: kuw1uLG1P4Dvzzm6MAIPx2e0fuYw+CracYEWVu9UBroeBkkaQh3ixmXM5HObvjfOPjyS/aoPDB3akHBU7IasR6sgq0itEfkY1WGeb5qht1flshbq0+uj4Cnl+WQRmKGN1lGRg7PaOrMtBVemW+DLO4MicuHfAwytsqLWzOO/J0XcIEUv9gDk34OoG93CIE3d7JOSQpVXdhZZBkhJVelPS4U3GcR7ONwAQLdDKMqi7AeNfSCFOxbU9BdyBuvHiMM6Mb5gCg6hglS8y5fYPj99u0H/K+JcKV1AOfBPiO05Y6wjdHBavYNZDjnxkZDD1QU6doSJ8cvhfq5XIM5QR+e6N71Fhn/SdWtyf6pqYAgWfL+pIb8+wo08T54O0S5jIYzrAk02pBwGe0+dG+06vXykW4B0zN/fag7YcPQ1iMEL86YZBYs0S3VuO8eWm3QBYzuNhkQylppyFXwONhKi2DS7Dx4laU5/547zjrCcPlswWGPQ7yji3Weml1fC2Rh6u+U3i3EM8eDNyzsddc/crAc5Kf47zUbrsBhsu5gfUUirzUXyxdde4UZWGxXv+Gr69SDVnRwrELBvCYdkRwKU9Y+alhAlF5xuuOh0TmVSOmOaEg3xjdWaenHywGxtUu1jr9xkOYXIhNt1qzque78xaQWGnHNOkSnu8u0czAHyrDoeo5M=
  - secure: kgrSUdoWSURUVcoEvnfXEbpKQIC+xUGfxKoEzljb67Kva+Z5z9HaFkc1LX7HoqxKIZpcoI7jfuHSG4Zu7vq0IWPxd9adDk1uEIe4Qj5YWv84fmIIOEO1vIVS/xdgYaFcuYASyMWBrimNgdP80/Iv7IhWYdZSTJKgJtufnYnTE6U5xC6wybWHEpnzjbMG/d8Qeocqs9KceZ58yFsQTv1O2lDJBPxtRX0bWE+GQcd7dcqKQhotedPluXLlXmAk1n+L/NJHvvT87hRLhKYTnY58ei9w6Ozg429a64Tux9paq7l0sGp6CA4OK0eCf01Tb05r8IpuHkV9A6FYWc9f6wRpUXrK72S2sgHkJapm9stVhAXvMvbiuG87DYfiyZHaDvmZnroFOr2CL4bu9VAXYVHDGQlrq4ua/PUBxUzRJSqdZxIYtRNILyz+8JreJy537W1788vsc8mGbHlB5hDoeZTYyDr3gk9uTY2FcZcpjrc8IdmLckfsUzYS7db/NjZJaKIcWIOHDN7BZtxuHoEfXVHC6Z3eduWCiY1zxV0wBheX3mSydh0IH5DLyxkm8gQ6GrZcMo33l/e5I0xAaaopF71kKhq3mhlSvcYaPgwbbQiP2cs7D0eiT8my/FJXgrOiBWuK78oPMeygst6o4GwFATrfVQMqz6KJu9H9byj+w1FYWJg=
  - secure: Mom+83SNOJe2YYjgUx8K8FEVtMTio8CIsSSk8CxkHk55HComGKgydJ0tN3XMof65/qj9VDxRAXdm0izPRGQQxBWlMz/8GvKwTEbwvxQ3XA1gHhT9HDbm4+lQTZYObSRuMzRGFzlYRk5gP9dQxGISYE8le53KhzLDCBdz0M9vicHg9Tzfk2mOKaZGYuTbLvlxe5JQFZCeh3VMLvL+1PZ0wAJWzEftg64wQRtm740uM+pH6MYy6Q072gO9t4NpOMM2q1nXJd1usG+9SP8X+Lo91Aby8x1V0N7/cb93VOKfHEgNzzp21KzGnKsQlTa8d0SyW7ZtgKsCH300HFkkqi6tvq/1qGE1rg2JrYceL4F27k6n+aG1jXj0Epuezj1aTgfuqLsGTxw0PzEI25KShyqcsJmYYY9hw142z3exETrJliVEB2C/72D1DWAOt2aKk4nl+ef7zpGFTTbG2X76V3dysZFaRz3kfHxvzmisMxSneSqPd3VqpmFR8kIAV/lZFMtU3RDcJHJkMVETyRwzrurs2Uvnx8HXZLAjQ/NG/+cGxwEY40yAYL3ugOk8HAJyxA868RYz2UwXSUV8AHhFys1Jy5LW4BTqo5g+GxYA2xliQ0mwiMc9D2w+B2WCyA6sdHIW8FVVDNS5QfpG7B6AALyNlYAACj6YRKhCpPuHetDMY0g=
